### ISSUE TITLE
Erros visuais

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#10]
Marcos,
Estou colocando aqui duas telas, uma certa que estou usando aqui na minha versão e outra que considero errado, mas talvez preciso saber apenas onde ajustar na hwgui em harbour.

1-Observe que a acentuação no titulo da janela funciona mas no groupbox não funciona corretamente.
2-Destquei em amarelo na errada que o SAY está por algum motivo quebrando o texto, mas eu gostaria que ele não quebrasse.
Só para complementar essa quebra de linha no SAY eu usava o AutoSize:=.T. para ficar correto, agora mesmo colocando como true ele ainda fica errado.
3-Observa que no BUTTONEX ele fica um espaço vazia a esquerda da imagem, em vez de alinhas a imagem bem a esquerda como padrão. ( mudando nPictureMargin de 0 para 1 resolve, mas achei que o padrão era 1 )

Errada(Habour+Mingw):
![tela errada](https://github.com/marcosgambeta/HWGUI/assets/4009697/d26d738f-1a68-4736-9881-1666d3ca32bb)

Certa(xHarbour+BCC72+Hwgui que estou usando desde que Kresin capou fora tudo)
![tela certa](https://github.com/marcosgambeta/HWGUI/assets/4009697/db24ddec-f216-4564-aac8-b10a002edf04)

**Comment by marcosgambeta** [comment]
Poderia testar e informar ser as linhas abaixo surgem algum efeito na acentuação (REQUEST e hb_cdpSelect) ?

```
#include "hwgui.ch"

REQUEST HB_CODEPAGE_PTISO

PROCEDURE Main()

   hb_cdpSelect("PTISO")

   // seu código   

RETURN
```

No seu sistema, está usando o GROUPBOX ou o GROUPBOX EXTENDED ?

**Comment by sygecom** [comment]
Vou testar o que indicou e, retorno em seguida.

Só uso: GROUPBOX 

Exemplo dessa ela ai
@ 5,5 GROUPBOX "Configuração de Conexão com Servidor" SIZE 590,225;
COLOR 16711680

**Comment by sygecom** [comment]
Eu já tinha em uso o REQUEST para xHarbour mesmo, mas mesmo colocando o hb_cdpSelect("PTISO") não deu certo, estranho que o problema acontece apenas no GROUPBOX do caso da acentuação.

![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/d1c68c84-9d18-4b35-9d01-cc1192236af8)

**Comment by sygecom** [comment]
1-Com o ajuste do Auto_Size que fez por ultimo resolveu 99% dos erros visuais da SAY, agora ficou pendente apenas a quebra de linha, que sei como resolver no sistema, mas eu gostaria de deixar como antes que se resolvia sozinho, vou abrir um outro caso para isso, para não misturar varios assuntos aqui no mesmo.

2-Sobre a configuração da acentuação fiz um teste colocando no TRANSPARENT na minha linha de código e isso forçou a usar a HGroupEx() em vez de HGroup() e resolveu o problema da acentuação, mesmo assim tinha um erro meu que a mesma tela eu chamava antes do hb_cdpselect('PTISO') e mudei e resolveu de vez para ambos os casos.
