### ISSUE TITLE
Error hcontrol

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#12]
Estou com esse erro abaixo em outra tela, vou tentar reproduzir um exemplo.

Error BASE/1081  Erro nos parƒmetros: +
Called from source\hcontrol.prg->HCONTROL:INIT(141)
Called from source\hcontrol.prg->HSTATIC:INIT(683)
Called from source\hstaticex.prg->HSTATICEX:INIT(123)
Called from source\guimain.prg->HWG_INITCONTROLS(73)
Called from source\hdialog.prg->INITMODALDLG(466)
Called from source\hdialog.prg->HDIALOG:ONEVENT(311)
Called from source\hdialog.prg->HWG_CREATEDLGINDIRECT(0)
Called from source\hdialog.prg->HDIALOG:ACTIVATE(151)
Called from source\SygFinanceiro\oSygFinanceiro.prg->OSYGFINANCEIRO:UILISTACONTAS(1129)
Called from source\sagi.prg->(b)MAIN(1076)
Called from source\hwindow.prg->ONCOMMAND(1200)
Called from source\hwindow.prg->HMAINWINDOW:ONEVENT(541)
Called from source\hwindow.prg->HWG_ACTIVATEMDIWINDOW(0)
Called from source\hwindow.prg->HMAINWINDOW:ACTIVATE(396)
Called from source\sagi.prg->MAIN(1702)

**Comment by sygecom** [comment]
O erro que acontece não consigo simular no a.prg, então tentei identificar colocando uns MSGINFO() antes da linha 137 do HCONTROL.PRG e consegui achar como chega o erro veja, se consegue me ajudar.

Hcontrol.prg original
![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/d0295c8d-3a71-4b64-973f-24cfbaa114e5)

Hcontrol.prg com minha validação:
![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/f1e84b0f-917e-4a44-a30d-96f159823f5d)

Veja a mensagem antes do erro, por que em algum momento ::nLeft chega NIL
![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/567e52d5-3a97-40bf-9782-f4b698578d86)

**Comment by marcosgambeta** [comment]
Embora não tenha conseguido reproduzir o erro aqui, encontrei uma situação suspeita na classe HStaticEx (note que ela é listada na mensagem de erro). Agora é preciso que você atualize e teste para confirmar ou não minha suspeita.
https://github.com/marcosgambeta/HWGUI/commit/b6020fa938ebcba6ea5f02f05a9c5abe6d866974

**Comment by sygecom** [comment]
vou testar

**Comment by sygecom** [comment]
Testado e resolveu, testei 3x vez, deletei meu HCONTROL.PRG para descartar minhas alterações e deu certo, você matou a charada.
Esse ajuste que fez, me abriu o caminho para eu tentar mexer no outro problema que tenho do AUTOZISE, vou ver se consigo resolver e comento no outro post.
