### ISSUE TITLE
Error a.prg

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#13]
Mestre,
Se adicionarmos no exemplo da pasta \samples\all\a.prg  e colocar no a.hbp as linhas abaixo:
a.prg
..\..\hwgui.hbc
hbwin.hbc
hbct.hbc
hbtip.hbc
-lxhb

E no inicio do a.prg as linhas abaixo:
#include "hbcompat.ch"
#include "hwgcompat.ch"

Da erro ao executar, será que estou fazendo algo erro ? estava querendo reproduzir um erro que tenho no hcontrol e não consigo sair dessa etapa.

**Comment by marcosgambeta** [comment]
No lugar de...

```
-lxhb
```

Use...

```
xhb.hbc
```

**Comment by sygecom** [comment]
deu certo.
