### ISSUE TITLE
Error htab

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#14]
Mestre.
Estou com um erro quando deleto uma aba no ON INIT  de uma DIALOG, se colocar no BUTTON para deletar não da erro, mas a tela fica toda bugada.

No exemplo abaixo da para simular os dois problemas o erro no ON INIT e se comentar o ON INIT ele abre a tela e, depois clica no botão excluir aba que simula o segundo problema visual.

STATIC FUNCTION ErrorPreview( cMess )
   LOCAL oDlg, oEdit, oTAB, oNOM, cNOM:='', oGroup1, oLabel7,oCNP, cCNP:='', nCL:=0, oGroup2, oButtonex2, oButtonex3
   LOCAL aPOS:={.T.,.T.,.T.}, oSEL, lSEL:=.F., oSta
   
   INIT DIALOG oDlg TITLE "Erro No Sistema SCM Vs. 1.0";
   ICON HIcon():AddResource(1004)  ;
   AT 0,0 SIZE GETDESKTOPWIDTH()-50,GETDESKTOPHEIGHT()-150;
   FONT HFont():Add( '',0,-13,400,,,) CLIPPER  NOEXIT NOEXITESC NOCLOSABLE;
   ON INIT {|| oTab:HidePage(2),oTab:DeletePage(2) };
   STYLE DS_CENTER+WS_VISIBLE+WS_CAPTION+WS_MINIMIZEBOX+WS_MAXIMIZEBOX+WS_SYSMENU+WS_SIZEBOX

   oDlg:minHeight := 450
   oDlg:minWidth := 1000

   @ 002,5 TAB oTab ITEMS {} SIZE oDlg:nWidth-10,oDlg:nHeight-150;
   ON GETFOCUS {|| oTab:SetFocus() };
   ON INIT {|oCtrl|oCtrl:bChange:={|o,nPage|oTab:settab(nPage), oTab:ChangePage(nPage)  } }
   
   BEGIN PAGE "&Dados 1" of oTab
      @ 05,30 EDITBOX oEdit CAPTION cMess SIZE oTab:nWidth-10,oTab:nHeight-150 STYLE WS_VSCROLL + WS_HSCROLL + ES_MULTILINE + ES_READONLY ;
      COLOR 255 ;
      FONT HFont():Add( '',0,-11,400,,,);
      ON GETFOCUS { || SendMessage( oEdit:handle, EM_SETSEL, 0, 0 ) }
   END PAGE of oTab
   
   BEGIN PAGE "&Dados 2" of oTab
      @ 001,30 GROUPBOX oGroup1 CAPTION "Filtros"  SIZE oTab:nWidth-10,140 STYLE BS_LEFT //COLOR x_BLUE
      oGroup1:Anchor := 11
      
      @ 10,60 GET oNOM VAR cNOM SIZE oGroup1:nWidth-20,24  PICTURE '@!' MAXLENGTH 100;
      TOOLTIP 'Selecione o campo a esquerda e digite aqui o que deseja buscar'
      oNOM:Anchor := 11

      @ oNOM:nLeft+01,oNOM:nTop+30 SAY oLabel7 CAPTION 'CNPJ/CPF:' TRANSPARENT SIZE 70,21
      oLabel7:Anchor:=8
      
      @ oLabel7:nWidth+10,oLabel7:nTop GET oCNP VAR cCNP SIZE 180,24 PICTURE '@!';
      TOOLTIP 'Informe o CNPJ ou o CPF'
      oCNP:Anchor:=8

      @ 001,oGroup1:nTop+oGroup1:nHeight GROUPBOX oGroup2 CAPTION "Contas"  SIZE oTab:nWidth-10,oTab:nHeight-180 STYLE BS_LEFT
      oGroup2:Anchor := 15
      
      @ oGroup2:nLeft+05,oGroup2:nTop+20 BROWSE oBr1 ARRAY SIZE oGroup2:nWidth-15,oGroup2:nHeight-90 STYLE WS_TABSTOP+WS_VSCROLL+WS_HSCROLL ;
      FONT HFont():Add( '',0,-11,400,,,)
      oBr1:Anchor := 15

      oBr1:aArray := {{.F.,'CONTA',DATE(),}}
      //                1   2       3      

      CreateArList( oBr1, oBr1:aArray )
      oBr1:aColumns[01]:lEDITABLE := .T.
      oBr1:aColumns[01]:bValid := {||  ShowMsg('Deu certo ?'),.t. }

      oBr1:aColumns[01]:heading := 'Sel'
      oBr1:aColumns[02]:heading := 'Tip Lancto'
      oBr1:aColumns[03]:heading := 'Data'
      
      oBr1:aColumns[01]:length := 03
      oBr1:aColumns[02]:length := 15
      oBr1:aColumns[03]:length := 13
      
      oBr1:aColumns[01]:picture:='@!'
      oBr1:aColumns[02]:picture:='@!'
      oBr1:aColumns[03]:picture:='@d'
      
      oBr1:aColumns[01]:bColorFoot := {|| {0 , 12632256} }
      oBr1:aColumns[02]:bColorFoot := {|| {0 , 12632256} }
      oBr1:aColumns[03]:bColorFoot := {|| {0 , 12632256} }
      
      oBr1:aColumns[01]:nJusHead:= DT_LEFT
      oBr1:aColumns[02]:nJusHead:= DT_LEFT
      oBr1:aColumns[03]:nJusHead:= DT_LEFT
      
      oBr1:aColumns[01]:bHeadClick := {|| IF(aPOS[01],( ASORT(oBr1:aArray,,,{|x,y|  x[01]<y[01] }),aPOS[01]:=.F.  ), ( ASORT(oBr1:aArray,,,{|x,y|  x[01]>y[01] }),aPOS[01]:=.T.  )  ), oBr1:REFRESH() }
      oBr1:aColumns[01]:bHeadClick := {|| IF(aPOS[02],( ASORT(oBr1:aArray,,,{|x,y|  x[02]<y[02] }),aPOS[01]:=.F.  ), ( ASORT(oBr1:aArray,,,{|x,y|  x[02]>y[02] }),aPOS[02]:=.T.  )  ), oBr1:REFRESH() }
      oBr1:aColumns[01]:bHeadClick := {|| IF(aPOS[03],( ASORT(oBr1:aArray,,,{|x,y|  x[03]<y[03] }),aPOS[01]:=.F.  ), ( ASORT(oBr1:aArray,,,{|x,y|  x[03]>y[03] }),aPOS[03]:=.T.  )  ), oBr1:REFRESH() }
      

      @ oBr1:nLeft,oBr1:nTop+oBr1:nHeight+8 GET CHECKBOX oSEL VAR lSEL CAPTION "Selecionar Tudo"  SIZE 130,22  ;
      TOOLTIP 'Selecione esta opção para marcar ou desmarcar todas as contas'
      oSEL:Anchor := 4

      nCL:=oGroup2:nLeft
      @ nCL,oSEL:nTop+30 BUTTONEX oButtonex2 CAPTION "&Excluir aba" SIZE 80,32;
      STYLE BS_CENTER+WS_TABSTOP;
      FONT HFont():Add( '',0,-11,400,,,);
      TOOLTIP 'Cadastrar um novo documento'
      oButtonex2:Anchor := 4
      
      nCL+=oButtonex2:nWidth
      @ nCL,oSEL:nTop+30 BUTTONEX oButtonex3 CAPTION "&Alterar" SIZE 80,32;
      STYLE BS_CENTER+WS_TABSTOP;
      FONT HFont():Add( '',0,-11,400,,,);
      TOOLTIP 'Alterar o documento selecionado'
      oButtonex3:Anchor := 4
   END PAGE of oTab
      
   @ oDlg:nWidth-120,oTab:nHeight+10 BUTTONEX "&Fechar" ON CLICK { || oDlg:CLOSE() } SIZE 100, 38 ;
   BITMAP (HBitmap():AddResource(1005)):handle  ;
   TOOLTIP 'Clique aqui para Fechar';
   STYLE WS_TABSTOP
   
   ADD STATUS oSta TO oDlg
   
   ACTIVATE DIALOG oDlg NOMODAL
   
RETURN Nil

**Comment by sygecom** [comment]
Posso fechar esse caso aqui, ou acha que podemos tentar ajustar esse problema visual apenas ?

**Comment by sygecom** [comment]
Marcos,
Tenho um outro problema com Htab que pode ser simulado na aquele exemplo a.prg que mandei e foi resolvido com -gc3.

Na aquele mesmo exemplo, se clicar nas abas, eles não muda e sempre fica na primeira aba, não gera um erro, mas também não troca de aba ao clicar.

**Comment by sygecom** [comment]
Com uma dica do José Quintas, para eu testar tirando o xhb.ch e xhb.hbc resolve o erro de clicar nas aba da htab. 

Vou me encarnar nisso e tentar remover do meu sistema tudo. Vai dar um baixa trabalho, mas acho que vale a pena.

**Comment by sygecom** [comment]
Não consegui eliminar ela toda, por que o SQLRDD me obriga a usar ela na força bruta, mas 
REQUEST XHB_LIB
REQUEST HB_Deserialize
REQUEST HB_Serialize

Outro caminho é tentar listar todas function que uso do xhb.lib e, tentar ir eliminando uma a uma para ver qual fica e causa o erro.

**Comment by sygecom** [comment]
Resolvido os clique da htab. 
1-tirando duas coisas: não usar xhb.ch e sim apenas: hbcompat.ch
2-retirei da xhb.lib os seguintes arquivos da compilação( xhbolec.c e xhbole.prg ) e resolveu o problema.

Em /hb/doc/xhb-diff.txt o Victor recomenda se livrar da lib e desses .ch 

No topico abaixo o Antonio até citou um problema com Ole
https://groups.google.com/g/harbour-devel/c/pHb7hOYL35s

Marcos,
Se achar pertinente posso encerrar esse ticket.

**Comment by marcosgambeta** [comment]
Sobre a SQLRDD, ela não está mais dependente da contrib/xhb. Movi alguns poucos arquivos para o repositório da SQLRDD e agora pode ser compilada sem o xhb.hbc. Quanto ao ticket, pode fechar.

**Comment by sygecom** [comment]
Eu vi agora pouco os commit do SQLRDD, muito bom, tu é o cara. vou fechar esse.
