### ISSUE TITLE
hcombo

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#15]
Mestre,
Antes os meus COMBOBOX de ARRAY iniciava já com o primeiro item do vetor selecionado, agora inicia vazio.

Eu alterei o METHOD New para no final dele adicionar as linhas abaixo, você acha que isso pode aplicar isso ai na hcombo ?

   if len(aItems)>0
      ::Setitem(1)
   endif

**Comment by marcosgambeta** [comment]
Nos meus testes, eu não consegui reproduzir este comportamento. Poderia comparar o modo como você faz com os exemplos adicionados recentemente:
https://github.com/marcosgambeta/HWGUI/commit/dc25275a7e82f66f51269358c14e699522187b49
https://github.com/marcosgambeta/HWGUI/commit/8f8b2e8555dc2069f2a07ab59137ce4ae856e259
No caso do comando @ x, y COMBOBOX, se usa o INIT para indicar o item selecionado. E no caso do @ x, y GET COMBOBOX, é utilizado o valor da variável.

**Comment by sygecom** [comment]
Acho que faltou uma informação minha que deveria ter colocado.
Eu uso TEXT em quase 100% dos meus combobox.

Veja o exemplo
@ 007,132 GET COMBOBOX oSTATUS VAR cSTATUS ITEMS {'Todas','Autorizada','Cancelada','Inutilizada','Não Transmitida','Terceiro','Denegada','Impressão FSDA'} SIZE 145,24 TEXT;
          ON CHANGE {|| IIF(cSTATUS='Não Transmitida' .OR. cSTATUS='Impressão FSDA', (nORI:=2,oORI:SETVALUE(2),oORI:REFRESH()), ),.T.  };
          TOOLTIP 'Selecione o status'

**Comment by sygecom** [comment]
vou tentar montar um exemplo do meu problema com combobox e, em breve trago aqui.

**Comment by sygecom** [comment]
Acho que consegui reproduzir dois problemas em um só, claro que digo problemas por que no xharbour+hwgui(minha versão antiga) eu não tenho esses dois problemas.

1-Erro se tiver um ON INIT + SETITEM em GET COMBOBOX se não tiver TEXT no comando.
2-Ao iniciar o GET COMBOBOX ele inicia na posição errada do vetor.

Ambos exemplos pode ser simulado na FUNCTION abaixo que é a mesma que esta no A.PRG da pasta SAMPLES.

```
FUNCTION DialogFromPrg(o)

   LOCAL cTitle := "Dialog from prg", cText := "Input something"
   LOCAL oModDlg
   LOCAL oFont := HFont():Add("MS Sans Serif", 0, -13)
   LOCAL cRes, aCombo := {"First", "Second"}, oEdit, vard := "Monday"
   LOCAL cCOMBO:='Second',oCOMBO
   // LOCAL aTabs := {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday"}

   // o:bGetFocus := NIL

   INIT DIALOG oModDlg TITLE cTitle AT 210, 10 SIZE 300, 300 FONT oFont ;
      ON EXIT {||hwg_Msgyesno("Really exit ?")}

   @ 20, 10 SAY cText SIZE 260, 22
   @ 20, 35 EDITBOX oEdit CAPTION ""    ;
        STYLE WS_DLGFRAME              ;
        SIZE 260, 26 COLOR hwg_VColor("FF0000")

   @ 20, 70 CHECKBOX "Check 1" SIZE 90, 20
   @ 20, 95 CHECKBOX "Check 2"  ;
        SIZE 90, 20 COLOR Iif(nColor == NIL, hwg_VColor("0000FF"), nColor)

   @ 160, 70 GROUPBOX "RadioGroup" SIZE 130, 75

   RADIOGROUP
   @ 180, 90 RADIOBUTTON "Radio 1"  ;
        SIZE 90, 20 ON CLICK {||oEdit:SetColor(hwg_VColor("0000FF"), , .T.)}
   @ 180, 115 RADIOBUTTON "Radio 2" ;
        SIZE 90, 20 ON CLICK {||oEdit:SetColor(hwg_VColor("FF0000"), , .T.)}
   END RADIOGROUP SELECTED 2

   @ 20, 120 GET COMBOBOX oCOMBO VAR cCOMBO ITEMS aCombo STYLE WS_TABSTOP TEXT;
   ON INIT{|o| o:SETITEM(ASCAN(aCombo,{|x| ALLTRIM(x)=ALLTRIM(cCOMBO)}))};
   SIZE 120, 24
   
   @ 20, 160 UPDOWN 10 RANGE -10, 50 SIZE 50, 32 STYLE WS_BORDER

   @ 160, 150 TAB oTab ITEMS {} SIZE 130, 66
   BEGIN PAGE "Monday" OF oTab
      @ 20, 34 GET vard SIZE 80, 22 STYLE WS_BORDER
   END PAGE OF oTab
   BEGIN PAGE "Tuesday" OF oTab
      @ 20, 34 EDITBOX "" SIZE 80, 22 STYLE WS_BORDER
   END PAGE OF oTab

   @ 100, 220 LINE LENGTH 100

   @ 20, 240 BUTTON "Ok" OF oModDlg ID IDOK  ;
        SIZE 100, 32 COLOR hwg_VColor("FF0000")
   @ 140, 240 BUTTON "11" OF oModDlg  ;
        SIZE 20, 32 ON CLICK {|o|CreateC(o)}
   @ 180, 240 BUTTON "Cancel" OF oModDlg ID IDCANCEL  ;
        SIZE 100, 32

   ACTIVATE DIALOG oModDlg

   oFont:Release()

RETURN NIL

```

**Comment by sygecom** [comment]
já vi um commit no hcombo, vou testar da aqui uns min.

**Comment by marcosgambeta** [comment]
Esta alteração verifica se a variável usada no GET COMBOBOX é do tipo C, ativando a flag lText, mesmo que o desenvolvedor não tenha usado TEXT no comando. Nos testes aqui:
. se a variável for vazia, seleciona o primeiro item
. se tiver conteúdo e fazer parte da lista, seleciona o item correspondente
. se tiver conteúdo e não fazer parte da lista, não seleciona nada

**Comment by sygecom** [comment]
Marcos, 
A grande maioria dos problemas com combobox resolveu, ainda tenho 2 problemas com combobox, mas por algum motivo ainda não consegui simular ele no a.prg

1-Basicamente é iniciar na primeira posição do array, quando a variavel da combobox tiver vazia, tive que colocar isso abaixo no final do metodo new para resolver essa questão.
   if empty(::value)
      if len(aItems)>0
         ::Setitem(1)
      endif
   endif

2-Tenho espalhado no sistema alguns combobox que eu não queria mexer, mas que visivelmente está errado o uso. O exemplo abaixo, onde tenho um array com os nomes completos, mas o cMOD:='55' e funciona, acho que ele deve está respeitando o 
SET EXACT ON

![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/1996676c-bf2d-4665-a74d-1d46f21afa70)

combobox:
```
@ 180,016 SAY oLabel3 CAPTION "Modelo"  SIZE 47,21
@ 180,038 GET COMBOBOX oMOD VAR cMOD ITEMS aMOD SIZE 60,24 TEXT DISPLAYCOUNT 10;
          ON CHANGE{|| oOPE:SETTEXT(IF((LEFT(cMOD,2)='NS' .AND. GET_PARAMETRO('MEDICAO_NOVA',.T.)) .OR. ::lConjugada,'Saida',oOPE:GETTEXT())),;
                       oOPE:SETVALUE(IF((LEFT(cMOD,2)='NS' .AND. GET_PARAMETRO('MEDICAO_NOVA',.T.)) .OR. ::lConjugada,ASCAN(oOPE:aItems,'Saida'),ASCAN(oOPE:aItems,oOPE:GETTEXT()))),;
                       oOPE:ENABLE(),oOPE:REFRESH(),oOPE:onChange(),oOPE:REFRESH(),;
                       ::grAtualizaDadosNota(oDlg,'MOD',nNNFid)};
          TOOLTIP 'Selecione o modelo'

```

Meu ambiente: Harbour 3.2( ultimo commit do git) + Mingw 8.1.0 ( 32bits )
