### ISSUE TITLE
Erro HDIALOG

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#16]
Esse erro abaixo está difícil de simular nos exemplos. Essa linha 20512 é apenas um: Return(lRET) do final de um metodo de uma classe minha chamada:
Method uiIncluiProduto(cLAN,oOBJ,lSALVA_FECHA,cALT_NF_TRANS,cORIG,cSTAT,cTESTE,lDIVPREPROD,nNNFid,oPLANOnf) Class oSygFiscal

Error BASE/1078  Erro nos parƒmetros: .AND.
Called from source\SygFiscal\oSygFiscal.prg->OSYGFISCAL:UIINCLUIPRODUTO(20512)
Called from source\SygFiscal\oSygFiscal.prg->OSYGFISCAL:GRATUALIZAIMPOSTOPRODUTO(23713)
Called from source\SygFiscal\oSygFiscal.prg->(b)OSYGFISCAL_UILANCANOTAFISCAL(5728)
Called from source\hdialog.prg->INITMODALDLG(471)
Called from source\hdialog.prg->HDIALOG:ONEVENT(311)
Called from source\hdialog.prg->HWG_DLGBOXINDIRECT(0)
Called from source\hdialog.prg->HDIALOG:ACTIVATE(145)
Called from source\SygFiscal\oSygFiscal.prg->OSYGFISCAL:UILANCANOTAFISCAL(7640)
Called from source\SygFiscal\oSygFiscal.prg->(b)OSYGFISCAL_UILISTAFISCAL(1095)
Called from source\hbrowse.prg->HBROWSE:ONCLICK(2973)
Called from source\hbrowse.prg->HBROWSE:EDIT(2993)
Called from source\hbrowse.prg->HBROWSE:BUTTONDBL(2878)
Called from source\hbrowse.prg->HBROWSE:ONEVENT(793)
Called from source\hwindow.prg->HWG_ACTIVATEMDIWINDOW(0)
Called from source\hwindow.prg->HMAINWINDOW:ACTIVATE(396)
Called from source\sagi.prg->MAIN(1711)

Não faço ideia por que da esse erro, já analise toda hdialog

**Comment by sygecom** [comment]
Acho que é um conjunto de varias coisas usada na tela, percebi que as telas quando tem ON INIT e ON EXIT que o erro mais aparece, nas telas que não tem o erro não acontece.
Vou tentar montar o exemplo no a.prg

**Comment by sygecom** [comment]
Consegui colocar no a.prg a reprodução do problema.

Segue em anexo o a.prg, só compilar ele com hbmk2 a
E quando executar vai no menu: FILE > CADASTRO DE BANCO, depois que a tela abrir só clica no X pra fechar que da o erro.

[a.zip](https://github.com/marcosgambeta/HWGUI/files/14391595/a.zip)

Error:
Error BASE/1078  Argument error: .AND.
Called from a.prg->CAD_BANCO(1610)
Called from a.prg->(b)MAIN(46)
Called from source\hwindow.prg->ONCOMMAND(1208)
Called from source\hwindow.prg->HMAINWINDOW:ONEVENT(541)
Called from source\hwindow.prg->HWG_ACTIVATEMDIWINDOW(0)
Called from source\hwindow.prg->HMAINWINDOW:ACTIVATE(396)
Called from a.prg->MAIN(87)

HwGUI 2.17 Harbour 3.2.0dev (r2402130449)
Date:02/24/24
Time:00:26:34

**Comment by sygecom** [comment]
Só para fim de complementar.
Esse erro não acontece se compilar com xHarbour e Bcc 7.2.0

Como estou testando tudo com Harbour 3.2 e Mingw, são esses dois ambientes que tenho para testar.

Vou providenciar outros ambientes como: Harbour+Bcc, Harbour+Msvc

**Comment by sygecom** [comment]
Compilando com Harbour+Bcc72 também da erro, mas em linha diferente apenas.

**Comment by marcosgambeta** [comment]
Fiz um teste usando esta configuração:
```
#define PAGE_1_ENABLED 1
#define PAGE_2_ENABLED 0
#define PAGE_3_ENABLED 1
#define PAGE_4_ENABLED 1
#define PAGE_5_ENABLED 1
#define PAGE_6_ENABLED 1
#define PAGE_7_ENABLED 1
#define PAGE_8_ENABLED 1
#define PAGE_9_ENABLED 1
#define PAGE_10_ENABLED 1
```
A configuração acima dá erro, então desativei todos os controles da ABA 1.
Com todos os controles da ABA 1 desativados, fui ativando um por um e o erro surgiu quando ativei estas linhas:
```
@ 255,LI+144 SAY oLabelVlr_outramoe CAPTION "Saldo "  SIZE 60,22 TRANSPARENT ;
   ON INIT {|o| o:show() }
```
Mas continua sendo um erro estranho, pois o Harbour tem capacidade para lidar com uma quantidade grande de variáveis.
Testei também em 64-bit e o erro ocorre da mesma forma.

**Comment by marcosgambeta** [comment]
Esta é uma ideia não testada ainda.:
Tem muitos 'labels' nas abas cujo objetos são criados, mas não são utilizados de nenhuma forma depois.
Exemplo:
```
@ 010,LI+24 SAY oLabel1 CAPTION "N° do Caixa:"  SIZE 77,22 TRANSPARENT
```
Linhas assim poderiam ser modificadas, conforme exemplo abaixo:
```
@ 010,LI+24 SAY "N° do Caixa:"  SIZE 77,22 TRANSPARENT
```
O objeto criado ficaria restrito aos controles internos da HWGUI, não precisando o desenvolvedor criar uma variável para ele.
Pode ser que uma mudança assim ajude e o erro enigmático pare de ocorrer.

**Comment by marcosgambeta** [comment]
Uma possível solução:
```
hbmk2 a2 -gc3
```
Vai usar a VM do Harbour, mas de outra forma.
O parâmetro -gc3 gera binários maiores, mas são mais rápidos.
Sugiro adotar este parâmetro na compilação.

**Comment by JoseQuintas** [comment]
Reduzi a rotina, e cheguei nesta parte aqui:
'''   ACTIVATE DIALOG oDlg

   hwg_MsgInfo( "aqui fechou dialog" )

   RETURN Nil
'''
A mensagem é exibida normalmente, só depois dá erro

'''      MENUITEM "&Cadastro de banco" ACTION { || CAD_BANCO(), hwg_MsgInfo( "teste" ) }

Dá erro entre entre as duas, não chega a executar msginfo()

Se apagar os dois primeiros label, funciona.
Se deixar os dois e apagar outra coisa, funciona.
Conforme o que apagar, aconteceu de ser acionada a rotina de progressbar, sem ter sido chamada.
NÃO dá pra considerar o que é apagado como sendo parte da solução.
Teve um momento onde apaguei uma função static fora de uso e o erro sumiu, mas nem é usada, como explicar?
Apenas chute: parece que os pointers para o aplicativo se perdem.
Fonte mais resumido ainda gerando erro
Nota: também acontece com hwgui atual, e funcionar no xharbour confunde a cabeça
[test.zip](https://github.com/marcosgambeta/HWGUI/files/14397438/test.zip)

**Comment by sygecom** [comment]
Mestre,
Posso até mudar no meu app são centenas de telas que deve ter SAY com uma variável não usada.
Tenho aproximadamente 12mil SAY que tem CAPTION na mesma linha, fora os que está na linha abaixo que as vez quebro com ;
Vou precisar analisar cada um deles para ver se da para tirar.

Minha teoria depois de testar com varios compiladores diferentes, é que com xharbour não da erro por que ele não destroi a janela quando fecha ela, ou seja de alguma forma fica na memoria e, o Harbour sim descarrega e por isso da o erro.
Abaixo os ambintes que teste.

Deu erro:
HARBOUR+BCC72 (32 BITS)
HARBOUR+BCC73 (32 BITS)
HARBOUR+BCC74 (32 BITS)
HARBOUR+MINGW32 (32 BITS)
HARBOUR+MINGW64 (64 BITS)
HARBOUR+MSVC (32 BITS)

Deu certo:
XHARBOUR+BCC72 ( B2 BITS)
XHARBOUR+BCC73 ( B2 BITS)
XHARBOUR+BCC74 ( B2 BITS)
XHARBOUR+MSVC ( B2 BITS)

**Comment by sygecom** [comment]
> Uma possível solução:
> 
> ```
> hbmk2 a2 -gc3
> ```
> 
> Vai usar a VM do Harbour, mas de outra forma. O parâmetro -gc3 gera binários maiores, mas são mais rápidos. Sugiro adotar este parâmetro na compilação.

Obrigado e, vou testar.

**Comment by marcosgambeta** [comment]
Se o parâmetro -gc3 resolver, então pode até desconsiderar a mudança no SAY.

**Comment by sygecom** [comment]
No a.prg resolveu, agora estou compilando minha aplicação inteira para testar, em breve já digo algo e se resolver, encerro esse ticket aqui.
Tenho centenas de outros problemas ainda para resolver, precisava tirar esse da frente.

**Comment by sygecom** [comment]
Demora para compilar com esse -gc3, mas vou aguardar até terminar, já está uns quase 20 min compilando. E um total de 519 .prg e um pouco mais de um milhão de linhas. Vou aguardar kkkkkk

![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/6120f5f3-6893-4c68-82a8-53387b1f5d6a)

**Comment by marcosgambeta** [comment]
Usando o parâmetro -jobs, você pode acelerar a compilação. Na próxima vez que compilar a HWGUI, experimente assim:
```
hbmk2 hwguiall.hbp -jobs=2
```
Pode ser um valor maior que 2. Você pode usar como base a quantidade de núcleos do seu computador, mas com 2 já se nota a diferença.

**Comment by sygecom** [comment]
Já estou usando 4 apesar do meu ter 8, mas sei que tem colegas meu que só tem 4 núcleos. 
Ainda está compilando com esse parâmetro kkkkk vou esperar, depois vou reiniciar a maquina e tentar tudo de novo, pode ser coincidência de ter dado alguma coisa errada no meu windows.

Uma duvai, devo recompilar as LIB Hwgui e Sqlrdd com esse -gc3 ?

**Comment by marcosgambeta** [comment]
Minha recomendação é que use o parâmetro na compilação das bibliotecas também. Embora seja algo opcional, se ganha no desempenho.

**Comment by sygecom** [comment]
perfeito, vou adotar aqui para tudo então. Obrigado pela dica valiosa.

O meu app ainda segue compilando kkkkkkkkk
Vou manter o ticket aberto até testar no meu sistema.

**Comment by sygecom** [comment]
Marcos,
Esperei por uma hora e não saiu dessa tela abaixo depois que coloquei o -gc3 
![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/e4987d12-d8ea-42f9-bbf4-72d5acd5e53c)

Segue em anexo o .prg e .ch que está compilando e travando na hora de compilar.
[fastreport.zip](https://github.com/marcosgambeta/HWGUI/files/14397928/fastreport.zip)

Será que teria alguma outra dica para deixar a compilação mais rápida ?

**Comment by marcosgambeta** [comment]
Você usa o parâmetro -inc (compilação incremental) ?
Neste caso, se compila apenas o código que sofreu alterações.
É SSD ou HD ?

**Comment by sygecom** [comment]
Sim, uso o -INC o problema está na primeira compilação do zero mesmo, que não sai do lugar.

Sim, aqui é um SSD, 24gb de memoria e 8 nucleos

**Comment by sygecom** [comment]
Compilando com Harbour+Bcc72 pelo menos ele da um erro ao final em vez de travar, como trava usando harbour+ming32

Turbo Incremental Link 6.90 Copyright (c) 1997-2017 Embarcadero Technologies, Inc.
Warning: BSS                 : 0x00000000 / 0x01000000
Warning: CODE                : 0x0032e624 / 0x01000000
Warning: DATA                : 0x000a40e4 / 0x01000000
Warning: DEBSYM              : 0x0000000e / 0x01000000
Warning: Extdef flags        : 0x0000033c / 0x00008000
Warning: Extdefs             : 0x00000cf0 / 0x00008000
Warning: INIT                : 0x00000006 / 0x01000000
Warning: Import symbols      : 0x00000000 / 0x00100000
Warning: OBJ symbols         : 0x0000a900 / 0x00400000
Warning: Public GSX          : 0x00000370 / 0x000c0000
Warning: Publics             : 0x00001ef0 / 0x000c0000
Warning: SegRelocs           : 0x005c3460 / 0x00800000
Warning: StringBlock         : 0x0000002e / 0x01000000
Warning: Virdefs             : 0x00000008 / 0x00020000
Warning: CODE                : 0x0057aecd / 0x01000000
Warning: D:/sistemas/sagi/trunk/SAGI_MINGW32.ilc: 0x042b9000 / 0x08000000
Warning: D:/sistemas/sagi/trunk/SAGI_MINGW32.ild: 0x00da7000 / 0x08000000
Warning: D:/sistemas/sagi/trunk/SAGI_MINGW32.ilf: 0x01898000 / 0x0a000000
Warning: D:/sistemas/sagi/trunk/SAGI_MINGW32.ils: 0x0009e000 / 0x08000000
Warning: D:/sistemas/sagi/trunk/SAGI_MINGW32.tds: 0x00020000 / 0x09400000
Warning: DATA                : 0x000af5a8 / 0x01000000
Warning: Extdef flags        : 0x0000021d / 0x00008000
Warning: Extdefs             : 0x00000874 / 0x00008000
Warning: INIT                : 0x00000006 / 0x01000000
Warning: Import symbols      : 0x00000000 / 0x00100000
Warning: OBJ symbols         : 0x00000000 / 0x00400000
Warning: Public GSX          : 0x000000a4 / 0x000c0000
Warning: Publics             : 0x000005c4 / 0x000c0000
Warning: SegRelocs           : 0x007ffd14 / 0x00800000
Warning: StringBlock         : 0x00000015 / 0x01000000
Warning: Virdefs             : 0x00000000 / 0x00020000
Warning: unknown heap name   : 0x08000000 / 0x08000000
Fatal: Exceeded memory limit for block SegRelocs in module obj_bcc\oSygFiscal.c
hbmk2[sagi_hb]: Erro: Executando linkeditor. 2

**Comment by sygecom** [comment]
Acho que tenho que dar uma partida nos .PRG muito grande, tem um com 73mil linhas vou tentar dividir em vários arquivos os muitos grande e volto aqui para dar um feedback.

**Comment by sygecom** [comment]
Fiz mais um teste, agora compilando harbour+Mingw64 e demorou o inicial, mas compilou até o fim. O que indica que o problema acontece apenas com 32bits.
O José Quintas me deu uma dica que ainda vou testar que seria eu usar o harbour compilado em 64 bits, para compilar projetos 32 bits, vou tentar fazer isso.

**Comment by marcosgambeta** [comment]
No caso do erro com o BCC, você pode tentar dividir este arquivo oSygFiscal em dois:
```
Fatal: Exceeded memory limit for block SegRelocs in module obj_bcc\oSygFiscal.c
```
Os arquivos .c gerados com o -gc3 são maiores. Se for um prg muito grande, o arquivo .c será bem maior e o .obj poderá exceder o limite.

**Comment by marcosgambeta** [comment]
Seu sistema num único executável mostra ser bem grande. Talvez seja possível transformar os diferentes módulos em DLL's.

**Comment by sygecom** [comment]
> Seu sistema num único executável mostra ser bem grande. Talvez seja possível transformar os diferentes módulos em DLL's.

Está na minha lista aqui para fazer essa divisão em módulos de DLL ou talvez em .HRG, chegarei lá.
De momento vou dividir os .PRG para testar de novo com BCC(32BITS) e MING32(32bits)

**Comment by sygecom** [comment]
> Seu sistema num único executável mostra ser bem grande. Talvez seja possível transformar os diferentes módulos em DLL's.

Está na minha lista aqui para fazer essa divisão em modulos de DLL ou talvez em .HRG, chegarei lá.
De momento vou dividir os .PRG para testar de novo com BCC(32BITS) e MING32(32bits)

**Comment by sygecom** [comment]
Só pra encerrar esse tópico, consegui quebrar diversos .PRG enormes que eu tenho em vários pequenos e deu certo com BCC72, com MINGW ainda não, mas o caminho é por ai. Obrigado pela ajuda e vou encerrando esse ticket.
