### ISSUE TITLE
Duvida hwgcompat.ch

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#17]
Marcos,
Por que no hwgcompat.ch tem duas vez a linha abaixo ?
#xtranslate Redrawwindow([<n,...>])           => hwg_Redrawwindow(<n>)

Estou eliminando o uso dela no meu sistema e me deparei por isso, a duvida é apenas para conhecimento, mas acredito que deve está sem querer duplicado.

**Comment by marcosgambeta** [comment]
Obrigado por avisar.
Dever ser um erro mesmo. Já vem do código original da versão 2.17.
Já está corrigido no commit abaixo:
https://github.com/marcosgambeta/HWGUI/commit/432cd2f86e149150b724cdb1358b92680151471b

**Comment by marcosgambeta** [comment]
Além do arquivo hwgcompat.ch, tem mais uma alternativa agora. Veja os commits abaixo:

https://github.com/marcosgambeta/HWGUI/commit/cc1482c211020ee46af2adf74368d554301e53e6
https://github.com/marcosgambeta/HWGUI/commit/9f414a013296b6915d45741c1cf53908163d00df
https://github.com/marcosgambeta/HWGUI/commit/1938f87891664c75c124a67f24093516d07235b4
https://github.com/marcosgambeta/HWGUI/commit/298cdedd7506baae668d5b50fc10cae503c75c26

Talvez ajude a ganhar mais tempo para fazer as mudanças, sem os problemas gerados pelo arquivo hwgcompat,ch.

**Comment by sygecom** [comment]
Show mestre, vou baixar e partir para minhas mudanças até encontrar o que causa incompatibilidade, abraços.
