### ISSUE TITLE
hbrowse

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#19]
Marcos,
Estou com um erro no browse que ainda não consegui simular no a.prg. 

Parte do código que da erro.
      FOR mI := 1 TO Len(oBr1:aColumns)
         oBr1:aColumns[mI]:bColorBlock := {|| IF( !EMPTY(oBr1:aArray[oBr1:nCURRENT,2]) , {x_BLUE,x_YELLOW,x_GREEN,x_CYAN},;
                                              IF( oBr1:aArray[oBr1:nCURRENT,4]<0,{x_RED,x_WHITE,x_GREEN,x_CYAN},{x_BLUE,x_WHITE,x_GREEN,x_CYAN} )) }
      NEXT

O erro da na linha 2126 do hbrowse:
![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/88acb483-6522-4de0-af8f-486775ba7f88)

o erro:
Error BASE/1073  Erro nos parƒmetros: <
Called from source\estoque_gui.prg->(b)STATUS_ESTOQUE(2086)
Called from source\hbrowse.prg->HBROWSE:LINEOUT(2126)
Called from source\hbrowse.prg->HBROWSE:PAINT(1511)
Called from source\hbrowse.prg->HBROWSE:ONEVENT(560)
Called from source\tabelas.prg->HWG_REDRAWWINDOW(0)
Called from source\hbrowse.prg->HBROWSE:REFRESH(3450)
Called from source\hbrowse.prg->HWG_CREATEARLIST(3562)
Called from source\estoque_gui.prg->FILTRA_NO_ARRAY(2683)
Called from ->(b)EVAL(1627)
Called from d:\devel\sygecom\syg_hmsg.prg->MSGRUN(104)
Called from source\estoque_gui.prg->(b)STATUS_ESTOQUE(1627)
Called from source\hbuttonx.prg->HBUTTONEX:ONCLICK(163)
Called from source\hbuttonx.prg->(b)HBUTTONX_NEW(76)
Called from source\hdialog.prg->ONDLGCOMMAND(647)
Called from source\hdialog.prg->HDIALOG:ONEVENT(287)
Called from source\hwindow.prg->HWG_ACTIVATEMDIWINDOW(0)
Called from source\hwindow.prg->HMAINWINDOW:ACTIVATE(396)
Called from source\sagi.prg->MAIN(1716)

Data e Hora........: 02/03/2024 - 09:49:46
Versão compilador..: HwGUI 2.17 Harbour 3.2.0dev (r2402161723)
Compilador C/C++...: Borland/Embarcadero C++ 7.4 (32-bit)
Banco de Dados.....: POSTGRESQL NATIVE - PostgreSQL 13.12, compiled by Visual C++ build 1914, 64-bit

O erro acontece com Mingw também.

De momento coloquei uns try para poder seguir com mais outros testes com hbrowse.
![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/a90ba494-0f1f-4685-882e-02248adb8061)

**Comment by marcosgambeta** [comment]
Baseado na mensagem de erro, estaria ocorrendo no codeblock:
```
FOR mI := 1 TO Len(oBr1:aColumns)
oBr1:aColumns[mI]:bColorBlock := {|| IF( !EMPTY(oBr1:aArray[oBr1:nCURRENT,2]) , {x_BLUE,x_YELLOW,x_GREEN,x_CYAN},;
IF( oBr1:aArray[oBr1:nCURRENT,4]<0,{x_RED,x_WHITE,x_GREEN,x_CYAN},{x_BLUE,x_WHITE,x_GREEN,x_CYAN} )) }
NEXT
```
Mais precisamente nesta parte:
```
oBr1:aArray[oBr1:nCURRENT,4]<0
```
Vou tentar reproduzir aqui.

**Comment by sygecom** [comment]
Mestre Marcos.
Estou quebrando a cabeça aqui com Hwgui e, resolvi fazer uma analise mais profunda quando usa a minha versão 2.17 e de quando usa essa sua versão 2.17.

Analisando a versão 2.17 que o Kresin congelou, ele só congelou depois de muitas tentativas de alterações para deixar compatível com GTK e Harbour, olhando pelo LOG e, acredito que nessa época não tinha ninguém usando ou testando a Hwgui e isso bagunçou e não ficou ninguém usando nesse meio tempo, com recursos mais avançado, somente o básico mesmo do SVN ou talvez nem o básico.

Eu comecei a comparar com os fontes que tenho e uso em xharbour, e achei diferenças gigantes.
Minha versão parou no commit 1908 e, olhando no pelo log do svn em 30/10/2012 o basso começou e tentar deixar compatível com harbour da época e, em seguida o Pavel Tsarenko, também começou a fazer mudanças para deixar compilando com 64 bits.

A partir do commit 1969(26/12/2012) o Kresin começou a fazer a limpeza, excluindo sem adicionar em outro lugar o que funcionava em Windows e, quase 6 meses(19/06/2013) depois de muitos commit ele oficialmente decretou que a 2.17 ia pro Branches, de qualquer jeito que estava na época, sem ter validado ou relato de usuários na época se servia ou não.

Meu erro foi não ter acompanhado a Hwgui do SVN na época mesmo com os problemas.

Agora que preciso do 64bits e Harbour, estou em um caminho que tenho que percorrer e gostaria de escutar sua opinião.

Alguns pensamentos meu.
1-Tento investir tempo em fazer essa minha versão 2.17 ( commit 1908 de 27/11/2012) rodar com harbour e Mingw64 ( nesse item pode faltar conhecimento da minha parte)

2-Tento criar uma classe minha de telas e migro tudo para essa classe e depois para outra GUI ou até mesmo HWGUI em versão mais estável( nesse item vou levar meses migrando o meu sistema que é grande)

3-Invisto nessa sua versão da Hwgui até chegarmos em corrigir todos os problemas, e tenho uma lista grande de vários componentes que está dando erro ainda mas estou tentando relatar aos poucos aqui para não perder o foco, mas tenho muitos problemas ainda com: SAY, DatePicker, BROWSE, GET, GET COMBOBOX, CHECKBOX, GRID, MDI(DIALOG) e etc...

4-Já tento migrar para versão do SVN da hwgui direto, problema lá que a versão xharbour que seria a primeira coisa que tenho que deixar compatível está abandonada e incompatível. Até abri uns tickets lá que não consigo nem compilar em xharbour. Falta alguém dando uns commit em xharbour e deixando compatível.

Sem compromisso por favor, fique a vontade em expressar sua opinião e, agradeço desde já.

**Comment by marcosgambeta** [comment]
Minha recomendação seria seguir o item 1 e deixar a atualização para uma HWGUI mais recente para uma etapa posterior.
Assim, você se concentraria na adaptação do sistema para Harbour + SQLRDD (32-bit/64-bit) e ganharia mais tempo para resolver a parte gráfica (GUI) depois.

Peguei uma cópia da HWGUI r1908 e coloquei num repositório privado. Com alguns ajustes, compilou sem erros gerando somente avisos do compilador.

Testei com:

Harbour + MinGW 32-bit: ok
Harbour + MinGW 64-bit: ok
Harbour + MSVC 32-bit: ok
Harbour + MSVC 64-bit: compilação OK, mas falhando na execução dos binários

Tem pendente um problema de múltipla definição, por causa do errorsys, mas nada que não possa ser resolvido.

Baseado nos testes que já fiz, é viável você continuar usando a HWGUI r1908 tanto com Harbour quanto com xHarbour.

Vou fazer mais testes o mais breve possível e  depois passo mais informações sobre eles.

**Comment by sygecom** [comment]
Mestre,
Obrigado pela sua indicação. É Importante pra mim lhe escutar.

Compilar com Harbour já consigo em:
Harbour + Mingw32
Harbour + Mingw64
Harbour + Bcc74(32 bits)

Tudo sem xhb.lib

Tenho alguns mal comportamento como clique na aba da Htab que não funciona, ou seja não troca de aba.
Em fim tenho bem menos problemas pra resolver.

**Comment by marcosgambeta** [comment]
O repositório que estou usando para testes agora está público:
https://github.com/marcosgambeta/hwgui-r1908

**Comment by marcosgambeta** [comment]
Entre a r1908 e a HWGUI 2.17 do branche (r2082) tem cerca de 170 commit's. Então, é de se esperar que os problemas sejam bem menos. Penso que agora é mais questão de testar e corrigir algum problema que surgir, sem a necessidade de fazer grandes ou muitas alterações no seu sistema. Fique a vontade para usar as seções Issues/Discussions do repositório citado acima.

**Comment by sygecom** [comment]
obrigado, vou iniciar as validações e testes, qualquer coisa reporto lá.
