### ISSUE TITLE
Erro com datepicker

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#4]
Tem duas declarações em .CH diferente uma tem o ON GETFOCUS e a outra não, acredito que a que tem é a correta.

\hwgui\include\guilib.ch
e
\hwgui\include\_datepicker.ch

**Comment by sygecom** [comment]
Agora que eu vi, uma tem o: [ <oPick> VAR ] e a outra não tem.

E pelo que vi uso das duas formas com e sem.

**Comment by marcosgambeta** [comment]
As duas são válidas. Uma trabalha apenas com o objeto (@ x, y DATEPICKER) e a outra usa uma variável (@ x, y GET DATEPICKER). Veja os testes que adicionei:
https://github.com/marcosgambeta/HWGUI/commit/916aac8393543a5d0ede7d8d7a516f8b754a5793
https://github.com/marcosgambeta/HWGUI/commit/4364d0f8ab8a3ebeecac161097c053dd35be9718
Numa janela de entrada de dados, geralmente vai ser utilizada a opção @ x, y GET DATEPICKER.

**Comment by sygecom** [comment]
entendido, foi falta de observação minha.
