### ISSUE TITLE
xHarbour

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#8]
Marcos,
Essa versão da Hwgui será que posso usar com xHarbour 1.2.3 e BCC 7.2 ?

Lhe pergunto por que estou na briga pra não perder a versão em produção em quanto migro tudo e, vi que manteve alguma coisa com xharbour.

![image](https://github.com/marcosgambeta/HWGUI/assets/4009697/92f940bc-6d9c-48fc-9fd0-a9cf640cc1ed)

**Comment by marcosgambeta** [comment]
Vou precisar fazer alguns ajustes e correções no código e nos scripts, mas aparentemente funciona:

```
#include "hwgui.ch"
#include "hbclass.ch"

PROCEDURE Main()

   LOCAL oDialog

   INIT DIALOG oDialog TITLE "Test" SIZE 640, 240

   @ 40, 40 SAY "xHarbour version: " + version() SIZE 500, 26

   @ 40, 80 SAY "Compiler version: " + hb_compiler() SIZE 500, 26

   ACTIVATE DIALOG oDialog

RETURN
```

![2024-02-18](https://github.com/marcosgambeta/HWGUI/assets/5998677/0028dc50-6368-4f42-912f-4bacf6e064b2)

Eu ainda não havia testado com o xHarbour.

A biblioteca source/activex apresenta erros na compilação com o BCC. Vou ter de revisar.

Atualizarei o repositório o mais breve possível.

**Comment by sygecom** [comment]
Obrigado pelo feedback. Assim que eu testar bem em Harbour vou ver se deixo a mesma para produção em xharbour até eu migrar tudo.
Esse activex nem uso mesmo, ela parou de funcionar faz tempo mesmo.

A noticia boa que consegui compilar meu sistema com Harbour+Ming32. Tem algumas coisas que está faltando, mas acredito que consigo aqui implementar nos fontes.

Uma delas o metod abaixo na HCONTROL, acredito que isso se perdeu com o Kresin fez uma limpa no código. Mas vou resolvendo aqui e, abro apenas os que eu não conseguir resolver.

METHOD FontBold( lTrue ) CLASS HControl
   Local oFont

   IF ::oFont = NIL
      IF ::GetParentForm() != Nil .AND. ::GetParentForm():oFont != Nil
         oFont := ::GetParentForm():oFont
      ELSEIF ::oParent:oFont != NIL
         oFont := ::oParent:oFont
      ENDIF
      IF oFont = Nil .AND. lTrue = Nil
          RETURN .T.
      ENDIF
      ::oFont := IIF( oFont != Nil, HFont():Add( oFont:name, oFont:Width,,,,,), HFont():Add( "", 0, , IIF( !Empty( lTrue ), FW_BOLD, FW_REGULAR ), ,,) )
   ENDIF
   IF lTrue != NIL
      ::oFont := ::oFont:SetFontStyle( lTrue )
      SendMessage( ::handle, WM_SETFONT, ::oFont:handle, MAKELPARAM( 0, 1 ) )
      RedrawWindow( ::handle, RDW_NOERASE + RDW_INVALIDATE + RDW_FRAME + RDW_INTERNALPAINT )
   ENDIF
   RETURN ::oFont:weight == FW_BOLD
