### ISSUE TITLE
Error HBROWSE:HWG_SETFOCUS

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/HWGUI#9]
Não estou conseguindo resolver esse erro, é um simples obrw:setfocus() em um BROWSE com DBF.

Error BASE/1004  Message not found: HBROWSE:HWG_SETFOCUS
Called from ../../../tobject.prg->__ERRRT_SBASE(0)
Called from ../../../tobject.prg->HBROWSE:ERROR(0)
Called from ../../../tobject.prg->(b)HBOBJECT(0)
Called from ../../../tobject.prg->HBROWSE:MSGNOTFOUND(0)
Called from ../../../tobject.prg->HBROWSE:HWG_SETFOCUS(0)
Called from source\syg_rdd.prg->ATUALIZA_SERVIDOR(1719)
Called from source\syg_rdd.prg->(b)CONFIGURA_SERVIDOR(1672)
Called from source\hctrlex.prg->HBUTTONEX:ONCLICK(163)
Called from source\hctrlex.prg->(b)HBUTTONX_NEW(76)
Called from source\hdialog.prg->ONDLGCOMMAND(647)
Called from source\hdialog.prg->HDIALOG:ONEVENT(287)
Called from source\hdialog.prg->HWG_DLGBOXINDIRECT(0)
Called from source\hdialog.prg->HDIALOG:ACTIVATE(145)
Called from source\syg_rdd.prg->CONFIGURA_SERVIDOR(1686)
Called from source\sagi.prg->MAIN(361)

Abaixo parte da tela, vou tentar montar um exemplo mais completo do erro.
[exemplo.txt](https://github.com/marcosgambeta/HWGUI/files/14326074/exemplo.txt)

**Comment by marcosgambeta** [comment]
Pelo que vi no exemplo.txt, o método SetFocus está sendo usado corretamente. Mas está virando um hwg_SetFocus e causando erro. Você está usando aquele arquivo .ch que traduz os nomes de funções, adicionando um hwg_ na frente ? Foi o primeiro suspeito em quem pensei.

```
#xtranslate Setfocus([<n,...>])               => hwg_Setfocus(<n>)
```

**Comment by sygecom** [comment]
Eu sempre uso:
oBrw:setfocus()
E nunca:
setfocus(obrw)

**Comment by sygecom** [comment]
Era isso mesmo chefe, deixei comentado aqui e vou seguir nos testes.
Depois que tudo der certo nos testes iniciais, pretendo deixar de usar o hwgcompat.ch migrando todas as chamadas para os nomes originais.
